### ISSUE TITLE
Bug report on the pandas merge lecture

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-datascience.myst#198]
From @jstac and an emailed bug report from Guilaume
```
I was looking at the merge part of the Pandas lecture in the QE for data science series.
The airline example part has a code that does not work: The airline code does not match with the descriptions.
It looks like replacing

avg_delays_w_code = avg_delays.join(carrier_code )

 by

avg_delays_w_code = avg_delays.merge(carrier_code, left_index = True, right_on = 'Code')

does the trick.
```
@wupeifan  Fyi.  @jbrightuniverse  could help fix if you concur with this.

**Comment by wupeifan** [comment]
I don't know whether it's a bug or not because it's working well on my side. After all, `pd.join` is exactly equivalent to what the `merge` line does. Maybe @jbrightuniverse can help verify whether this is indeed a problem?

**Comment by jlperla** [comment]
Totally up to you Peifan if you think this is expected behavior

**Comment by jbrightuniverse** [comment]
When I copy the example and run it on my end in a Python script, I get the same set of NaN entries.

When I use the fix `avg_delays_w_code = avg_delays.merge(carrier_code, left_index = True, right_on = 'Code')`, it works.

According to the documentation at https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.join.html, the `join()` function without specifying any keys will join "index on index" (not entirely sure what that's referring to). I haven't debugged far enough to determine why it shows up as all NaN because of that, but the merge line works for sure because its specifically linking through the `Code` from the RHS database linked to the existing order of entries on the left.

For reference, we currently see this:
![image](https://user-images.githubusercontent.com/30967260/148113192-625c05d9-5b4b-43f2-b7f9-343d8362e8c8.png)
I think we should be seeing this instead:
![image](https://user-images.githubusercontent.com/30967260/148113242-5bd5c8e0-c06e-489c-bd1c-d517309118da.png)

**Comment by jbrightuniverse** [comment]
It could have something to do with the left dataset not having a specified index; I can check this later today.

**Comment by wupeifan** [comment]
@jbrightuniverse Thanks, let me have a look at this. It could be because of different versions of Pandas (because it worked well on the Syzygy server).

**Comment by wupeifan** [comment]
OK. This is because `pd.read_csv` changed its default behavior by setting an additional level of numerical indices.
Change `avg_delays_w_code = avg_delays.join(carrier_code )` to `avg_delays_w_code = avg_delays.join(carrier_code.set_index("Code")` would be a minimal working adjustment.
